<?php
/**
 * PostBusinessModelExceptionsCreateRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Stackflows\Clients\Stackflows
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stackflows REST API
 *
 * Pagination query params are as follows: page[size]=10&page[number]=1
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Stackflows\Clients\Stackflows\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PostBusinessModelExceptionsCreateRequestTest Class Doc Comment
 *
 * @category    Class
 * @description PostBusinessModelExceptionsCreateRequest
 * @package     Stackflows\Clients\Stackflows
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PostBusinessModelExceptionsCreateRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PostBusinessModelExceptionsCreateRequest"
     */
    public function testPostBusinessModelExceptionsCreateRequest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "solution"
     */
    public function testPropertySolution()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "consequences"
     */
    public function testPropertyConsequences()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "incidence"
     */
    public function testPropertyIncidence()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "impact"
     */
    public function testPropertyImpact()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "causativeOrganizationUnitId"
     */
    public function testPropertyCausativeOrganizationUnitId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "responsibleOrganizationUnitId"
     */
    public function testPropertyResponsibleOrganizationUnitId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
