<?php
/**
 * VariableTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Stackflows\GatewayApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stackflows Gateway API
 *
 * Stackflows Gateway API
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: you@your-company.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Stackflows\GatewayApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * VariableTest Class Doc Comment
 *
 * @category    Class
 * @description Variable
 * @package     Stackflows\GatewayApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class VariableTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Variable"
     */
    public function testVariable()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "valueInfo"
     */
    public function testPropertyValueInfo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
