<?php
/**
 * CategoriesApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Stackflows\Clients\Stackflows
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stackflows REST API
 *
 * Pagination query params are as follows: page[size]=10&page[number]=1
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Stackflows\Clients\Stackflows\Test\Api;

use \Stackflows\Clients\Stackflows\Configuration;
use \Stackflows\Clients\Stackflows\ApiException;
use \Stackflows\Clients\Stackflows\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CategoriesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Stackflows\Clients\Stackflows
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CategoriesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for categoriesCreate
     *
     * Create.
     *
     */
    public function testCategoriesCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for categoriesDelete
     *
     * Delete.
     *
     */
    public function testCategoriesDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for categoriesList
     *
     * List.
     *
     */
    public function testCategoriesList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for categoriesShow
     *
     * View.
     *
     */
    public function testCategoriesShow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for categoriesUpdate
     *
     * Update.
     *
     */
    public function testCategoriesUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
