<?php
/**
 * EnvironmentApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Stackflows\Clients\Stackflows
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stackflows REST API
 *
 * Pagination query params are as follows: page[size]=10&page[number]=1
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Stackflows\Clients\Stackflows\Test\Api;

use \Stackflows\Clients\Stackflows\Configuration;
use \Stackflows\Clients\Stackflows\ApiException;
use \Stackflows\Clients\Stackflows\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EnvironmentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Stackflows\Clients\Stackflows
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EnvironmentApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for authBusinessModelDiagramsCommentsCreate
     *
     * Create Business Model Diagram Comment.
     *
     */
    public function testAuthBusinessModelDiagramsCommentsCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authBusinessModelDiagramsCommentsDelete
     *
     * Delete Business Model Diagram Comment.
     *
     */
    public function testAuthBusinessModelDiagramsCommentsDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authBusinessModelDiagramsCommentsList
     *
     * List Business Model Diagram Comments.
     *
     */
    public function testAuthBusinessModelDiagramsCommentsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authBusinessModelDiagramsCreate
     *
     * Create Business Model Diagram.
     *
     */
    public function testAuthBusinessModelDiagramsCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authBusinessModelDiagramsDelete
     *
     * Delete Business Model Diagram.
     *
     */
    public function testAuthBusinessModelDiagramsDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authBusinessModelDiagramsList
     *
     * List Business Model Diagram.
     *
     */
    public function testAuthBusinessModelDiagramsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authBusinessModelDiagramsPublish
     *
     * Publish Business Model Diagram.
     *
     */
    public function testAuthBusinessModelDiagramsPublish()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authBusinessModelDiagramsShow
     *
     * View Business Model Diagram.
     *
     */
    public function testAuthBusinessModelDiagramsShow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authBusinessModelsCommentsList
     *
     * List Business Model Comments.
     *
     */
    public function testAuthBusinessModelsCommentsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authBusinessModelsCreate
     *
     * Create Business Model.
     *
     */
    public function testAuthBusinessModelsCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authBusinessModelsDelete
     *
     * Delete Business Model.
     *
     */
    public function testAuthBusinessModelsDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authBusinessModelsList
     *
     * List Business Models.
     *
     */
    public function testAuthBusinessModelsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authBusinessModelsShow
     *
     * View Business Model.
     *
     */
    public function testAuthBusinessModelsShow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authServiceTasksLock
     *
     * Lock Service Tasks.
     *
     */
    public function testAuthServiceTasksLock()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authServiceTasksServe
     *
     * Serve Service Task.
     *
     */
    public function testAuthServiceTasksServe()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authServiceTasksUnlock
     *
     * Unlock Service Task.
     *
     */
    public function testAuthServiceTasksUnlock()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authTaggedBusinessModelsStart
     *
     * Starts Business Process Models by Tag.
     *
     */
    public function testAuthTaggedBusinessModelsStart()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authUserTasksComplete
     *
     * Complete User Task.
     *
     */
    public function testAuthUserTasksComplete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authUserTasksErrorize
     *
     * Errorize User Task.
     *
     */
    public function testAuthUserTasksErrorize()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authUserTasksEscalate
     *
     * Escalate User Task.
     *
     */
    public function testAuthUserTasksEscalate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for authUserTasksIndex
     *
     * List User Tasks.
     *
     */
    public function testAuthUserTasksIndex()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
