<?php
/**
 * EnvironmentApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Stackflows\Clients\Stackflows
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stackflows REST API
 *
 * Pagination query params are as follows: page[size]=10&page[number]=1
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Stackflows\Clients\Stackflows\Test\Api;

use \Stackflows\Clients\Stackflows\Configuration;
use \Stackflows\Clients\Stackflows\ApiException;
use \Stackflows\Clients\Stackflows\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * EnvironmentApiTest Class Doc Comment
 *
 * @category Class
 * @package  Stackflows\Clients\Stackflows
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EnvironmentApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteEnvironmentBusinessModelDiagrams
     *
     * Delete Business Model Diagram.
     *
     */
    public function testDeleteEnvironmentBusinessModelDiagrams()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteEnvironmentBusinessModelDiagramsComments
     *
     * Delete Business Model Diagram Comment.
     *
     */
    public function testDeleteEnvironmentBusinessModelDiagramsComments()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteEnvironmentBusinessModels
     *
     * Delete Business Model.
     *
     */
    public function testDeleteEnvironmentBusinessModels()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEnvironmentBusinessModelDiagramsCommentsList
     *
     * List Business Model Diagram Comments.
     *
     */
    public function testGetEnvironmentBusinessModelDiagramsCommentsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEnvironmentBusinessModelDiagramsList
     *
     * List Business Model Diagram.
     *
     */
    public function testGetEnvironmentBusinessModelDiagramsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEnvironmentBusinessModelDiagramsShow
     *
     * View Business Model Diagram.
     *
     */
    public function testGetEnvironmentBusinessModelDiagramsShow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEnvironmentBusinessModelsCommentsList
     *
     * List Business Model Comments.
     *
     */
    public function testGetEnvironmentBusinessModelsCommentsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEnvironmentBusinessModelsList
     *
     * List Business Models.
     *
     */
    public function testGetEnvironmentBusinessModelsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEnvironmentBusinessModelsShow
     *
     * View Business Model.
     *
     */
    public function testGetEnvironmentBusinessModelsShow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getEnvironmentUserTasksList
     *
     * List User Tasks.
     *
     */
    public function testGetEnvironmentUserTasksList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postEnvironmentBusinessModelDiagramsCommentsCreate
     *
     * Create Business Model Diagram Comment.
     *
     */
    public function testPostEnvironmentBusinessModelDiagramsCommentsCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postEnvironmentBusinessModelDiagramsCreate
     *
     * Create Business Model Diagram.
     *
     */
    public function testPostEnvironmentBusinessModelDiagramsCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postEnvironmentBusinessModelDiagramsPublish
     *
     * Publish Business Model Diagram.
     *
     */
    public function testPostEnvironmentBusinessModelDiagramsPublish()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postEnvironmentBusinessModelsCreate
     *
     * Create Business Model.
     *
     */
    public function testPostEnvironmentBusinessModelsCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postEnvironmentEventsMessage
     *
     * Send Message.
     *
     */
    public function testPostEnvironmentEventsMessage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postEnvironmentEventsSignal
     *
     * Send Message.
     *
     */
    public function testPostEnvironmentEventsSignal()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postEnvironmentServiceTasksLock
     *
     * Lock Service Tasks.
     *
     */
    public function testPostEnvironmentServiceTasksLock()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postEnvironmentServiceTasksServe
     *
     * Serve Service Task.
     *
     */
    public function testPostEnvironmentServiceTasksServe()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postEnvironmentServiceTasksUnlock
     *
     * Unlock Service Task.
     *
     */
    public function testPostEnvironmentServiceTasksUnlock()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postEnvironmentTaggedBusinessModelsStart
     *
     * Starts Business Process Models by Tag.
     *
     */
    public function testPostEnvironmentTaggedBusinessModelsStart()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postEnvironmentUserTasksComplete
     *
     * Complete User Task.
     *
     */
    public function testPostEnvironmentUserTasksComplete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postEnvironmentUserTasksErrorize
     *
     * Errorize User Task.
     *
     */
    public function testPostEnvironmentUserTasksErrorize()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postEnvironmentUserTasksEscalate
     *
     * Escalate User Task.
     *
     */
    public function testPostEnvironmentUserTasksEscalate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
