<?php
/**
 * OperationsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Stackflows\Clients\Stackflows
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stackflows REST API
 *
 * Pagination query params are as follows: page[size]=10&page[number]=1
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Stackflows\Clients\Stackflows\Test\Api;

use \Stackflows\Clients\Stackflows\Configuration;
use \Stackflows\Clients\Stackflows\ApiException;
use \Stackflows\Clients\Stackflows\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OperationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Stackflows\Clients\Stackflows
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OperationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for businessModelDiagramsCommentsCreate
     *
     * Create Business Model Diagram Comment.
     *
     */
    public function testBusinessModelDiagramsCommentsCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelDiagramsCommentsDelete
     *
     * Delete Business Model Diagram Comment.
     *
     */
    public function testBusinessModelDiagramsCommentsDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelDiagramsCommentsList
     *
     * List Business Model Diagram Comments.
     *
     */
    public function testBusinessModelDiagramsCommentsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelDiagramsCreate
     *
     * Create Business Model Diagram.
     *
     */
    public function testBusinessModelDiagramsCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelDiagramsDelete
     *
     * Delete Business Model Diagram.
     *
     */
    public function testBusinessModelDiagramsDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelDiagramsList
     *
     * List Business Model Diagram.
     *
     */
    public function testBusinessModelDiagramsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelDiagramsPublish
     *
     * Publish Business Model Diagram.
     *
     */
    public function testBusinessModelDiagramsPublish()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelDiagramsShow
     *
     * View Business Model Diagram.
     *
     */
    public function testBusinessModelDiagramsShow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelDiagramsUpdate
     *
     * Update Business Model Diagram.
     *
     */
    public function testBusinessModelDiagramsUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelExceptionsCreate
     *
     * Create Business Model Exception.
     *
     */
    public function testBusinessModelExceptionsCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelExceptionsDelete
     *
     * Delete Business Model Exception.
     *
     */
    public function testBusinessModelExceptionsDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelExceptionsList
     *
     * List Business Model Exceptions.
     *
     */
    public function testBusinessModelExceptionsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelExceptionsShow
     *
     * View Business Model Exception.
     *
     */
    public function testBusinessModelExceptionsShow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelExceptionsUpdate
     *
     * Update Business Model Exception.
     *
     */
    public function testBusinessModelExceptionsUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelPublicationsList
     *
     * List Business Model Publications.
     *
     */
    public function testBusinessModelPublicationsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelPublicationsShow
     *
     * View Business Model Publication.
     *
     */
    public function testBusinessModelPublicationsShow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelsCommentsList
     *
     * List Business Model Comments.
     *
     */
    public function testBusinessModelsCommentsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelsCreate
     *
     * Create Business Model.
     *
     */
    public function testBusinessModelsCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelsDelete
     *
     * Delete Business Model.
     *
     */
    public function testBusinessModelsDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelsDeleteBulk
     *
     * Delete Business Models.
     *
     */
    public function testBusinessModelsDeleteBulk()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelsList
     *
     * List Business Models.
     *
     */
    public function testBusinessModelsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelsPostRevision
     *
     * Submit Business Model Diagram.
     *
     */
    public function testBusinessModelsPostRevision()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelsShow
     *
     * View Business Model.
     *
     */
    public function testBusinessModelsShow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelsShowRevision
     *
     * View Business Model Diagram.
     *
     */
    public function testBusinessModelsShowRevision()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelsShowRevisions
     *
     * List Business Model Disgrams.
     *
     */
    public function testBusinessModelsShowRevisions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelsTag
     *
     * Tag Business Model.
     *
     */
    public function testBusinessModelsTag()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessModelsUpdate
     *
     * Update Business Model.
     *
     */
    public function testBusinessModelsUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessProcessesCreate
     *
     * Create Business Process Tag.
     *
     */
    public function testBusinessProcessesCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessProcessesDelete
     *
     * Delete Business Process Tag.
     *
     */
    public function testBusinessProcessesDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessProcessesDeleteBulk
     *
     * Delete Business Process Tags.
     *
     */
    public function testBusinessProcessesDeleteBulk()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessProcessesList
     *
     * List Business Process Tags.
     *
     */
    public function testBusinessProcessesList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessProcessesShow
     *
     * View Business Process Tag.
     *
     */
    public function testBusinessProcessesShow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for businessProcessesUpdate
     *
     * Update Business Process Tag.
     *
     */
    public function testBusinessProcessesUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for categoriesCreate
     *
     * Create Category.
     *
     */
    public function testCategoriesCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for categoriesDelete
     *
     * Delete Category.
     *
     */
    public function testCategoriesDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for categoriesList
     *
     * List Categories.
     *
     */
    public function testCategoriesList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for categoriesShow
     *
     * View Category.
     *
     */
    public function testCategoriesShow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for categoriesUpdate
     *
     * Update Category.
     *
     */
    public function testCategoriesUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tagsCreate
     *
     * Create Tag.
     *
     */
    public function testTagsCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tagsDelete
     *
     * Delete Tag.
     *
     */
    public function testTagsDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tagsList
     *
     * List Tags.
     *
     */
    public function testTagsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tagsShow
     *
     * View Tag.
     *
     */
    public function testTagsShow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tagsUpdate
     *
     * Update Tag.
     *
     */
    public function testTagsUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tasksCreate
     *
     * Create Task.
     *
     */
    public function testTasksCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tasksDelete
     *
     * Delete Task.
     *
     */
    public function testTasksDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tasksList
     *
     * List Tasks.
     *
     */
    public function testTasksList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tasksShow
     *
     * View Task.
     *
     */
    public function testTasksShow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tasksUpdate
     *
     * Update Task.
     *
     */
    public function testTasksUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
