<?php
/**
 * UserApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Stackflows\Clients\Stackflows
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stackflows REST API
 *
 * Pagination query params are as follows: page[size]=10&page[number]=1
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Stackflows\Clients\Stackflows\Test\Api;

use \Stackflows\Clients\Stackflows\Configuration;
use \Stackflows\Clients\Stackflows\ApiException;
use \Stackflows\Clients\Stackflows\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * UserApiTest Class Doc Comment
 *
 * @category Class
 * @package  Stackflows\Clients\Stackflows
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class UserApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteUserOrganizationsDelete
     *
     * Delete Organization.
     *
     */
    public function testDeleteUserOrganizationsDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteUserRevoke
     *
     * Revoke all tokens.
     *
     */
    public function testDeleteUserRevoke()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserMe
     *
     * Me.
     *
     */
    public function testGetUserMe()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserOrganizationsList
     *
     * List Organizations.
     *
     */
    public function testGetUserOrganizationsList()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getUserOrganizationsShow
     *
     * View Organization.
     *
     */
    public function testGetUserOrganizationsShow()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postUserLogin
     *
     * Login.
     *
     */
    public function testPostUserLogin()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postUserOrganizationsStore
     *
     * Create Organization.
     *
     */
    public function testPostUserOrganizationsStore()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postUserRegister
     *
     * Register.
     *
     */
    public function testPostUserRegister()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postUserResetPassword
     *
     * Restore password.
     *
     */
    public function testPostUserResetPassword()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putUserOrganizationsUpdate
     *
     * Update Organization.
     *
     */
    public function testPutUserOrganizationsUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putUserUpdate
     *
     * Update.
     *
     */
    public function testPutUserUpdate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
